auths:
  - !oidc
      issuer: https://token.actions.githubusercontent.com
      rules:
        - claims:
            iss: https://token.actions.githubusercontent.com
            aud: https://github.com/diondokter
            repository: diondokter/teleprobe-experiment
  # - !token
  #     token: my-very-secret-token
targets:
  - name: nrf52840-dk
    chip: nRF52840_xxAA
    probe: 1366:1015:000683703433